## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "The Bitcoin and the Bible Podcast"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-GFXNDPSECL"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner-white.png"
  favicon = true

[Params.social]
  github = "https://github.com/bitcoin-and-the-bible/"
  twitter = "https://twitter.com/btc4believers"
  email = "bitcoinandthebible@gmail.com"